<Project>
	<PropertyGroup>
		<LangVersion>preview</LangVersion>
		<Version>4.6.6</Version>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<Authors>百小僧</Authors>
		<Company>百签科技（广东）有限公司</Company>
		<Product>Jaina</Product>
		<Copyright>© 2020-2026 百小僧及百签科技（广东）有限公司</Copyright>
		<RepositoryUrl>https://gitee.com/dotnetchina/Jaina</RepositoryUrl>
		<RepositoryType>Gitee</RepositoryType>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://gitee.com/dotnetchina/Jaina</PackageProjectUrl>
		<PackageOutputPath>../nupkgs</PackageOutputPath>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSource>true</EmbedUntrackedSource>
		<EmbedAllSources>true</EmbedAllSources>
		<PackageIcon>icon.png</PackageIcon>
	</PropertyGroup>

	<PropertyGroup>
		<DocumentationFile>$(MSBuildProjectName).xml</DocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\Directory.Build.props" Pack="true" PackagePath="\"/>
		<None Include="..\icon.png" Pack="true" PackagePath="\"/>
		<None Include="..\..\README.md" Pack="true" PackagePath="\"/>
	</ItemGroup>

</Project>